spin_manifest_version = 2

[application]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
authors = ["{{authors}}"]
description = "{{project-description}}"

[[trigger.http]]
route = "{{http-path}}"
component = "{{project-name | kebab_case}}"
executor = { type = "wagi" }

[component.{{project-name | kebab_case}}]
source = "main.wasm"
allowed_outbound_hosts = []
[component.{{project-name | kebab_case}}.build]
command = "swiftc -target wasm32-unknown-wasi main.swift -o main.wasm"
watch = ["**/*.swift"]
